name: Build project

on: push

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -webGLCompressionFormat Disabled
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: 1

  deploy:
    needs: buildForAllSupportedPlatforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download WebGL Build
        uses: actions/download-artifact@v3
        with:
          name: Build-WebGL
          path: temp-build

      - name: Move WebGL files to root and setup headers
        run: |
          mv temp-build/WebGL/* temp-build/
          rm -rf temp-build/WebGL
          touch temp-build/.nojekyll

          # Создаем файл _headers с расширенными правилами
          echo "/*.br" >> temp-build/_headers
          echo "  Content-Encoding: br" >> temp-build/_headers
          echo "/*.js.br" >> temp-build/_headers
          echo "  Content-Type: application/javascript" >> temp-build/_headers
          echo "/*.data.br" >> temp-build/_headers
          echo "  Content-Type: application/octet-stream" >> temp-build/_headers
          echo "/*.wasm.br" >> temp-build/_headers
          echo "  Content-Type: application/wasm" >> temp-build/_headers

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: temp-build
          branch: gh-pages
          clean: true
